#!/bin/bash
echo "||| Configuration du serveur Split |||"
nbValidator=20
network="devnet"
port="57243"

sudo sed -i "s/#Port 22/Port 57243/" /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
yes | sudo ufw reset
sudo sed -i 's/IPV6=yes/IPV6=no/' /etc/default/ufw
sudo ufw allow 57243
sudo ufw allow 37373:38383/tcp
yes | sudo ufw enable
sudo service ssh restart
sudo apt update && sudo apt upgrade -y
sudo timedatectl set-timezone Europe/Paris
sudo apt install -y git-all zip unzip

cd ~ && git clone https://github.com/multiversx/mx-chain-scripts && cd mx-chain-scripts/config

sudo sed -i "s/22/$port/g" ~/mx-chain-scripts/config/variables.cfg
sudo sed -i "s/CUSTOM_HOME=\"\"/CUSTOM_HOME=\"/home/$(id -un)\"/" ~/mx-chain-scripts/config/variables.cfg
sudo sed -i "s/CUSTOM_USER=\"\"/CUSTOM_USER=\"$(id -un)\"/" ~/mx-chain-scripts/config/variables.cfg
sudo sed -i "s/ENVIRONMENT=\"\"/ENVIRONMENT=\"$network\"/" ~/mx-chain-scripts/config/variables.cfg

validators_list=$(printf "%s\n" "$nbValidator"; for i in $(seq 1 $nbValidator); do printf "Split-%02d\n" "$i"; done)
echo "$validators_list" | ~/mx-chain-scripts/script.sh install
cd ~

mkdir -p ~/VALIDATOR_KEYS

for i in $(seq 0 $nbValidator); do
  ~/./elrond-utils/keygenerator
  zip ~/elrond-nodes/node-$i.zip ~/validatorKey.pem
  mv ~/elrond-nodes/node-$i.zip $HOME/VALIDATOR_KEYS/
  mv validatorKey.pem ~/elrond-nodes/node-$i/config/
done

echo "Configuration terminée"
echo "Résumé de configuration :"
echo "Port : $port"
echo "Réseau : $network"
echo "Nombre de noeud installé : $nbValidator"
echo "Liste des noeuds :"
for i in $(seq 1 $nbValidator); do
  printf "Split-%03d\n" $i
done
