#!/bin/bash
# Script de configuration initiale des validateurs Synergy

echo "||| Configuration du serveur Synergy |||"

read -p "Quel port souhaitez-vous utiliser pour vos noeud(s) validateur(s) (entre 49152 et 65535) ? " port
read -p "Choix du réseau d'installation (mainnet, devnet, testnet) ? " typeofvalidator
read -p "Nombre de validateur à installer ? " nbvalidator

sudo sed -i "s/#Port 22/Port $port/" /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
yes | sudo ufw reset
sudo sed -i 's/IPV6=yes/IPV6=no/' /etc/default/ufw
sudo ufw allow $port
sudo ufw allow 37373:38383/tcp
yes | sudo ufw enable
sudo service ssh restart
sudo apt update && sudo apt upgrade -y
sudo timedatectl set-timezone Europe/Paris
sudo apt install -y git-all zip unzip
cd ~
git clone https://github.com/multiversx/mx-chain-scripts
cd ~/mx-chain-scripts/config

sudo sed -i "s/22/$port/g" ~/mx-chain-scripts/config/variables.cfg
sudo sed -i "s/ENVIRONMENT=\"\"/ENVIRONMENT=\"$typeofvalidator\"/" ~/mx-chain-scripts/config/variables.cfg

echo "$nbvalidator" >> ~/mx-chain-scripts/validatorsinstall
for i in $(seq 1 $nbvalidator); do
  echo "Synergy-$i" >> ~/mx-chain-scripts/validatorsinstall
done

~/mx-chain-scripts/script.sh install < validatorsinstall
cd ~
mkdir -p ~/VALIDATOR_KEYS

for i in $(seq 1 $nbvalidator); do
  ./elrond-utils/keygenerator
  zip node-$i.zip validatorKey.pem
  mv node-$i.zip $HOME/VALIDATOR_KEYS/
  mv validatorKey.pem $HOME/elrond-nodes/node-$i/config/
done

echo "Configuration de base terminée"
echo "Résumé de configuration :"
echo "Port : $port"
echo "Réseau : $typeofvalidator"
echo "Nombre de noeud installé : $nbvalidator"
echo "Liste des noeuds :"
for i in $(seq 1 $nbvalidator); do
  printf "Synergy-%03d\n" $i
done
echo "Reboot du serveur en cours.."
